### ISSUE TITLE
Not compiled with GPU support

### ISSUE THREAD

**Issue by ztb520** [JialianW/TraDeS#10]
When I tried to run the demo, there was an error Not Compiled with GPU support. Is it because I'm using the CUDA version? I tried to use Cuda9.0 and Cuda10.1, but this error occurred in both cases. What version of CUDA is running in your environment?

**Comment by ztb520** [comment]
Using tracking threshold for out threshold! 0.4
Fix size testing.
training chunk_sizes: [32]
input h w: 544 960
heads {'hm': 1, 'reg': 2, 'wh': 2, 'ltrb_amodal': 4}
weights {'hm': 1, 'reg': 1, 'wh': 0.1, 'ltrb_amodal': 0.1, 'cost_volume': 1.0}
head conv {'hm': [256], 'reg': [256], 'wh': [256], 'ltrb_amodal': [256]}
Creating model...
Using node type: (<class 'model.networks.dla.DeformConv'>, <class 'model.networks.dla.DeformConv'>)
Warning: No ImageNet pretrain!!
loaded ../models/mot_half.pth, epoch 70
OpenCV: FFMPEG: tag 0x44495658/'XVID' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Initialize tracking!
Traceback (most recent call last):
  File "demo.py", line 129, in <module>
    demo(opt)
  File "demo.py", line 84, in demo
    ret = detector.run(img)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/detector.py", line 127, in run
    images, self.pre_images, self.pre_hms, return_time=True)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/detector.py", line 399, in process
    output, current_feat = self.model(images, pre_images, pre_hms, inference_feats=self.inference_feats, addtional_pre_imgs=self.inference_preim, addtional_pre_hms=self.inference_prehm)
  File "/home/user/anaconda3/envs/trades/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/model/networks/base_model.py", line 150, in forward
    cur_feat = self.img2feats(x)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/model/networks/dla.py", line 603, in img2feats
    x = self.dla_up(x)
  File "/home/user/anaconda3/envs/trades/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/model/networks/dla.py", line 553, in forward
    ida(layers, len(layers) -i - 2, len(layers))
  File "/home/user/anaconda3/envs/trades/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/model/networks/dla.py", line 524, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/user/anaconda3/envs/trades/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/model/networks/dla.py", line 497, in forward
    x = self.conv(x)
  File "/home/user/anaconda3/envs/trades/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/model/networks/DCNv2/dcn_v2.py", line 128, in forward
    self.deformable_groups)
  File "/home/user/anaconda3/envs/TraDeS/src/lib/model/networks/DCNv2/dcn_v2.py", line 31, in forward
    ctx.deformable_groups)
RuntimeError: Not compiled with GPU support (dcn_v2_forward at /home/user/anaconda3/envs/TraDeS/src/lib/model/networks/DCNv2/src/dcn_v2.h:35)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7f52fe1f9687 in /home/user/anaconda3/envs/trades/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: dcn_v2_forward(at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, at::Tensor const&, int, int, int, int, int, int, int, int, int) + 0x178 (0x7f52e9e83c18 in /home/user/anaconda3/envs/TraDeS/src/lib/model/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x193cb (0x7f52e9e913cb in /home/user/anaconda3/envs/TraDeS/src/lib/model/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x15c7c (0x7f52e9e8dc7c in /home/user/anaconda3/envs/TraDeS/src/lib/model/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #10: THPFunction_apply(_object*, _object*) + 0x9ff (0x7f532e54690f in /home/user/anaconda3/envs/trades/lib/python3.6/site-packages/torch/lib/libtorch_python.so)

Aborted (core dumped)
exit status 134

**Comment by JialianW** [comment]
The cuda installation command is shown in the INSTALL.md as:

conda install pytorch=1.3.1 torchvision=0.4.2 cudatoolkit=10.0.130 -c pytorch

**Comment by ztb520** [comment]
I have completed downloading according to this command, but there is still such an error, which is inexplicable.

**Comment by ztb520** [comment]
When I run the file setup.py, the following error occurs:No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'

**Comment by xiaoweidao** [comment]
I followed the installation command to complete the download, and I also had this error. So I changed the environment and it ran successfully
python = 3.7
conda install pytorch=1.3 torchvision cudatoolkit=10.1 -c pytorch

**Comment by ztb520** [comment]
> I followed the installation command to complete the download, and I also had this error. So I changed the environment and it ran successfully
> python = 3.7
> conda install pytorch=1.3 torchvision cudatoolkit=10.1 -c pytorch

I successfully run the program, but now there is a new error：Aborted (core dumped)exit status 134, when frame=200.Have you ever met this mistake？

**Comment by xiaoweidao** [comment]
> > I followed the installation command to complete the download, and I also had this error. So I changed the environment and it ran successfully
> > python = 3.7
> > conda install pytorch=1.3 torchvision cudatoolkit=10.1 -c pytorch
> 
> I successfully run the program, but now there is a new error：Aborted (core dumped)exit status 134, when frame=200.Have you ever met this mistake？


I'm sorry, I didn't encounter this problem

**Comment by ztb520** [comment]
> > > I followed the installation command to complete the download, and I also had this error. So I changed the environment and it ran successfully
> > > python = 3.7
> > > conda install pytorch=1.3 torchvision cudatoolkit=10.1 -c pytorch
> > 
> > 
> > I successfully run the program, but now there is a new error：Aborted (core dumped)exit status 134, when frame=200.Have you ever met this mistake？
> 
> I'm sorry, I didn't encounter this problem

What is the final frame when you run the MOT demo? I can tell from the code that it looks like the program is over when frame = 200.

**Comment by ztb520** [comment]
> The cuda installation command is shown in the INSTALL.md as:
> 
> conda install pytorch=1.3.1 torchvision=0.4.2 cudatoolkit=10.0.130 -c pytorch

When I run the following command：sh experiments/mot17_train.sh，There's an error：FileNotFoundError: [Errno 2] No such file or directory: '/home/user/TraDeS_ROOT/src/lib/../../data/mot17/annotations/train_half.json'.

After running the command, I see the program looking for data:Using MOT 17 17halftrain
ann_file train_half.json
==> initializing train data from /home/user/TraDeS_ROOT/src/lib/../../data/mot17/annotations/train_half.json, 
 images from /home/user/TraDeS_ROOT/src/lib/../../data/mot17/train ...
loading annotations into memory...

But I can't find these files. There are no files in the folder. Why is that?
